### ISSUE TITLE
How is the serialize.js file generated?

### ISSUE THREAD

**Issue by hasanbayatme** [greymass/eosio-signing-request-java#3]
The file included inside the project called serialize.js seems to be generated from eosjs but I'm not sure how.

Is it a combination of eosjs + eosio-signing-request? if yes then how is it generated, either using webpack or something else? I'm looking for a more debuggable version of this file (not minified)

**Comment by poplexity** [comment]
Yes, I created it with webpack, I've attached a tarball of the repo that I built it with if you want to give it a shot, it was a couple years ago but should still work.  Note that this is an old version of the ESR repo and has a lot of extra stuff, you'll want to focus on the webpack config and the src/main.ts file.
[esrWebpack.tar.gz](https://github.com/greymass/eosio-signing-request-java/files/8266640/esrWebpack.tar.gz)


Edit: Closing this for now, feel free to reopen if you have questions, or find me on telegram @foflexity
